/* DiskMap FFI — generated by cbindgen. Do not edit. */

#ifndef DM_FFI_H
#define DM_FFI_H

/* Warning: this file is autogenerated by cbindgen. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Opaque handle to an in-progress or completed scan.
 */
typedef struct DmScanHandle DmScanHandle;

/**
 * Scan progress reported to the frontend.
 */
typedef struct DmScanProgress {
    uint64_t files_scanned;
    uint64_t dirs_scanned;
    uint64_t bytes_scanned;
    bool is_complete;
    bool has_error;
} DmScanProgress;

/**
 * A C-compatible array of strings.
 */
typedef struct DmStringArray {
    const char *const *strings;
    uint64_t count;
} DmStringArray;

/**
 * Result of a treemap layout computation.
 */
typedef struct DmTreemapResult {
    const DmTreemapRect *rects;
    uint64_t count;
} DmTreemapResult;

/**
 * Start an async scan. Returns an opaque handle.
 *
 * # Safety
 * `path` must be a valid null-terminated UTF-8 C string.
 */
struct DmScanHandle *dm_scan_start(const char *path);

/**
 * Poll for scan progress. Returns the latest progress.
 *
 * # Safety
 * `handle` must be a valid pointer from `dm_scan_start`.
 */
struct DmScanProgress dm_scan_poll(struct DmScanHandle *handle);

/**
 * Cancel an in-progress scan.
 *
 * # Safety
 * `handle` must be a valid pointer from `dm_scan_start`.
 */
void dm_scan_cancel(struct DmScanHandle *handle);

/**
 * Get the list of paths that need elevated access.
 *
 * # Safety
 * `handle` must be a valid pointer from `dm_scan_start`.
 * Caller must free the result with `dm_string_array_free`.
 */
struct DmStringArray dm_scan_denied_paths(const struct DmScanHandle *handle);

/**
 * Compute treemap layout for the current scan data.
 *
 * # Safety
 * `handle` must be a valid pointer with a completed scan.
 * Caller must free the result with `dm_treemap_free`.
 */
struct DmTreemapResult dm_treemap_layout(const struct DmScanHandle *handle,
                                         uint32_t root_index,
                                         float viewport_w,
                                         float viewport_h,
                                         uint16_t max_depth);

/**
 * Free a treemap layout result.
 *
 * # Safety
 * `result` must be from `dm_treemap_layout`.
 */
void dm_treemap_free(struct DmTreemapResult result);

/**
 * Get the display name for a node.
 *
 * # Safety
 * Caller must free the result with `dm_string_free`.
 */
char *dm_node_name(const struct DmScanHandle *handle, uint32_t node_index);

/**
 * Get the size of a node in bytes.
 *
 * # Safety
 * `handle` must be a valid pointer with a completed scan.
 */
uint64_t dm_node_size(const struct DmScanHandle *handle, uint32_t node_index);

/**
 * Check if a node is a denied/restricted directory.
 *
 * # Safety
 * `handle` must be a valid pointer with a completed scan.
 */
bool dm_node_is_denied(const struct DmScanHandle *handle, uint32_t node_index);

/**
 * Check if a node is a directory.
 *
 * # Safety
 * `handle` must be a valid pointer with a completed scan.
 */
bool dm_node_is_dir(const struct DmScanHandle *handle, uint32_t node_index);

/**
 * Get the root node index.
 *
 * # Safety
 * `handle` must be a valid pointer with a completed scan.
 */
uint32_t dm_root_index(const struct DmScanHandle *handle);

/**
 * Get the number of children for a node.
 *
 * # Safety
 * `handle` must be a valid pointer with a completed scan.
 */
uint32_t dm_node_child_count(const struct DmScanHandle *handle, uint32_t node_index);

/**
 * Get the node index of the Nth child of a node.
 *
 * # Safety
 * `handle` must be a valid pointer with a completed scan.
 * `child_offset` must be less than `dm_node_child_count`.
 */
uint32_t dm_node_child_at(const struct DmScanHandle *handle,
                          uint32_t node_index,
                          uint32_t child_offset);

/**
 * Get the total size of the scanned tree.
 *
 * # Safety
 * `handle` must be a valid pointer with a completed scan.
 */
uint64_t dm_total_size(const struct DmScanHandle *handle);

/**
 * Free a C string allocated by dm-ffi.
 *
 * # Safety
 * `s` must be from a dm-ffi function that returns `*mut c_char`.
 */
void dm_string_free(char *s);

/**
 * Free a string array allocated by dm-ffi.
 *
 * # Safety
 * `arr` must be from `dm_scan_denied_paths`.
 */
void dm_string_array_free(struct DmStringArray arr);

/**
 * Free a scan handle and all associated memory.
 *
 * # Safety
 * `handle` must be from `dm_scan_start`. Do not use after freeing.
 */
void dm_scan_free(struct DmScanHandle *handle);

#endif  /* DM_FFI_H */
